name: Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate Docs
        run: |
          cargo doc --no-deps --document-private-items
          cp ./LOGO.png ./target/doc/
          echo '<meta http-equiv="refresh" content="0; url=space_net/index.html">' > ./target/doc/index.html
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GH_TOKEN }}
          publish_dir: ./target/doc/
