name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --test voronoi --verbose
        cargo test --test test_boot --verbose
        cargo test --test test_node --verbose
        cargo test --test cluster --verbose
#    - name: Run stress tests
#      run: |
#        cargo test --release --test stress_test -- --ignored --nocapture